### ISSUE TITLE
The path of senteval

### ISSUE THREAD

**Issue by Jason98Xu** [SAP-samples/acl2022-self-contrastive-decorrelation#1]
Hi,
It is a great work! I just have one question when I ran your codes that the path of senteval in your original codes is PATH_TO_SENTEVAL = '/home/ubuntu/Local_SimCSE/SentEval', I think it might be a relative path like this PATH_TO_SENTEVAL = './SentEval', since for every user the path where they save data may be different? 

Thanks for your attention on this issue.

**Comment by TJKlein** [comment]
Yes, correct. It should definitely be the relative path. Thanks a lot for hinting at it.
