### ISSUE TITLE
A Question on paper about hyperparamter setting

### ISSUE THREAD

**Issue by HansiZeng** [SAP-samples/acl2022-self-contrastive-decorrelation#14]
In the paper, the final objective is defined as L = Ls + α * Lc, where Ls is to increase the contrast between two augmented embeddings and Lc is for feature decorrelation. In Table 3, an ablation study is conducted by removing individual losses. The results suggest that Lc is a more important loss than Ls, as only keeping Lc results in a higher score of 66.48 in the STS dataset compared to a score of 35.70 when only applying Ls loss. Intuitively, this makes sense as the two augmented embeddings are likely to be semantically similar, and Lc helps to decorrelate the features. However, in the experiment setting, the value of α is set to 0.005 (for BERT), which may indicate that Ls is more important when combined with Lc. Can you share your thoughts on why Lc appears more important in the ablation study but Ls appears more important when combined with Lc in the final objective? Thank you.

**Comment by TJKlein** [comment]
Thanks for your interest in our work. Minimizing Ls without regularization is susceptible to reaching one of the many local minima with suboptimal performance on the tasks with the solution space less restricted. On the other hand, the space of Lc is more restricted as it reduces redundancy. Redundancy reduction produces good features. But low redundancy is not sufficient.
