### ISSUE TITLE
question about reproduce

### ISSUE THREAD

**Issue by ShaobinChen-AH** [SAP-samples/acl2022-self-contrastive-decorrelation#15]
I try to follow your setting to reproduce the result of scd-roberta-base. However, there is an error "config.single_dropout not found" . 
How can I solve it..

**Comment by TJKlein** [comment]
There was still some legacy variable name in place. I fixed it by replacing it in 
```
transformers_v4.10/src/transformers/models/roberta/modeling_roberta.py
```
I have not tested it, but it should work now.
