### ISSUE TITLE
Figure 2

### ISSUE THREAD

**Issue by ShaobinChen-AH** [SAP-samples/acl2022-self-contrastive-decorrelation#3]
Hi! How do you draw figure 2? Can you provide the code? Thanks a lot!

**Comment by TJKlein** [comment]
Hi,
I added the source for the visualization to the repository: [link](https://github.com/SAP-samples/acl2022-self-contrastive-decorrelation/blob/main/visualization/alignment_vs_uniformity.ipynb)
